version: '3.8'

services:
  server:
    image: backend-dev
    build:
      context: .
      dockerfile: dev.Dockerfile
    volumes:
      - ./:/usr/src/app
    ports:
      - 3000:3000
    env_file:
      - .env
    container_name: backend-dev
