FROM node:16
  
WORKDIR /usr/src/app


COPY --chown=node:node . .
RUN npm ci 

ENV DEBUG=playground:*
ENV MONGO_URL=mongodb://the_username:the_password@localhost:3456/the_database
ENV REDIS_URL=localhost:6378
ENV PORT=3000


USER node
CMD npm start